-- 챗봇 피드백 확장 (관리자 챗봇 평가 수집)
-- AI_CHATBOT_FEEDBACK 에 권한 구분(AUDIENCE_CD) + 이슈 카테고리(ISSUE_CATEGORY) 컬럼 추가
-- 사용자/직원 피드백을 한 테이블에서 라벨로 분리

ALTER TABLE public."AI_CHATBOT_FEEDBACK"
    ADD COLUMN IF NOT EXISTS "AUDIENCE_CD" character(5) DEFAULT 'USER',
    ADD COLUMN IF NOT EXISTS "ISSUE_CATEGORY" character varying(40);

UPDATE public."AI_CHATBOT_FEEDBACK"
    SET "AUDIENCE_CD" = 'USER'
    WHERE "AUDIENCE_CD" IS NULL;

CREATE INDEX IF NOT EXISTS "ix_AI_CHATBOT_FEEDBACK_AUDIENCE"
    ON public."AI_CHATBOT_FEEDBACK" ("AUDIENCE_CD");

CREATE INDEX IF NOT EXISTS "ix_AI_CHATBOT_FEEDBACK_ISSUE"
    ON public."AI_CHATBOT_FEEDBACK" ("ISSUE_CATEGORY")
    WHERE "ISSUE_CATEGORY" IS NOT NULL;

COMMENT ON COLUMN public."AI_CHATBOT_FEEDBACK"."AUDIENCE_CD"
    IS 'USER(고객 챗봇) / ADMIN(직원 어시스턴트) — 피드백 신호 분리';
COMMENT ON COLUMN public."AI_CHATBOT_FEEDBACK"."ISSUE_CATEGORY"
    IS 'RETRIEVAL_MISS / ANSWER_INCORRECT / KNOWLEDGE_GAP / LENGTH / OTHER — 👎 카테고리';

-- 관리자 챗봇은 pseudo employee_no(990000+) 를 CUSTOMER_NO 컬럼에 매핑하므로
-- CUSTOMER FK 가 위반된다. AI_CHATBOT_SESSION 과 같은 방식으로 FK 제거.
ALTER TABLE public."AI_CHATBOT_FEEDBACK"
    DROP CONSTRAINT IF EXISTS "fk_ai_chatbot_feedback_customer_no";
